# Copyright (C) 2019 The ion-OS Project

# Set all versions
SQUID_BUILD_TYPE ?= UNOFFICIAL
SQUID_BUILD_DATE := $(shell date -u +%Y%m%d-%H%M)
SQUID_PLATFORM_VERSION := 9.0

 TARGET_PRODUCT_SHORT := $(subst squid_,,$(SQUID_BUILD))

 ifeq ($(IS_GO_VERSION), true)
SQUID_VERSION := squid-OS_go_$(SQUID_BUILD)-$(SQUID_PLATFORM_VERSION)-$(SQUID_BUILD_DATE)-$(SQUID_BUILD_TYPE)
SQUID_FINGERPRINT := squid-OS_go/$(SQUID_PLATFORM_VERSION)/$(TARGET_PRODUCT_SHORT)/$(SQUID_BUILD_DATE)
else
SQUID_VERSION := squid-OS_$(SQUID_BUILD)-$(SQUID_PLATFORM_VERSION)-$(SQUID_BUILD_DATE)-$(SQUID_BUILD_TYPE)
SQUID_FINGERPRINT := squid-OS/$(SQUID_PLATFORM_VERSION)/$(TARGET_PRODUCT_SHORT)/$(SQUID_BUILD_DATE)
endif

 ION_PROPERTIES := \
    ro.squid.version=$(SQUID_VERSION) \
    ro.squid.build_date=$(SQUID_BUILD_DATE) \
    ro.squid.build_type=$(SQUID_BUILD_TYPE) \
    ro.squid.fingerprint=$(SQUID_FINGERPRINT)
